# Generated by Django 4.2.17 on 2024-12-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_items_app', '0002_alter_customer_address_alter_seller_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='document',
            field=models.FileField(default=1, upload_to='document'),
            preserve_default=False,
        ),
    ]
