# Generated by Django 4.2.17 on 2024-12-31 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('old_items_app', '0003_seller_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
                ('photo', models.FileField(upload_to='product_photo/')),
                ('description', models.CharField(max_length=250)),
                ('seller_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='old_items_app.seller')),
            ],
        ),
    ]
