# Generated by Django 4.2.17 on 2025-01-14 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('old_items_app', '0005_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_details', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='old_items_app.customer')),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='old_items_app.product')),
            ],
        ),
    ]
