# Generated by Django 4.2.17 on 2025-01-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_items_app', '0006_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
