# Generated by Django 4.2.17 on 2025-01-16 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('old_items_app', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='old_items_app.customer'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='old_items_app.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
