# Generated by Django 4.2.17 on 2025-01-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_items_app', '0008_alter_cart_customer_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
