# Generated by Django 4.2.17 on 2025-01-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_items_app', '0010_alter_seller_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
