# Generated by Django 4.2.17 on 2025-01-21 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('old_items_app', '0011_alter_seller_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('customer_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='old_items_app.customer')),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='old_items_app.product')),
            ],
        ),
    ]
