# Generated by Django 4.2.17 on 2025-01-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_items_app', '0013_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='date',
        ),
        migrations.AddField(
            model_name='chat',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
