# Generated by Django 4.2.17 on 2025-01-30 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('old_items_app', '0014_remove_chat_date_chat_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='status_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='old_items_app.mystatus'),
            preserve_default=False,
        ),
    ]
